### ISSUE TITLE
error 1.20.6

### ISSUE THREAD

**Issue by danyadanya2005** [imDaniX/WGExtender#1] opened 2024-05-29 14:19 UTC
https://pastebin.com/xYxcMAiF

**Comment by imDaniX** [comment] 2024-06-06 11:09
See https://github.com/imDaniX/WGExtender/releases/tag/v3.1.1
Resolved with https://github.com/imDaniX/WGExtender/commit/20c55a08c32855c20b6aa947ae87bb5cf87462e2

I've only test auto-flags feature, so no guarantee everything works as intended. In such case, create a new issue.

**Closed by imDaniX** 2024-06-06 11:09 UTC

**Comment by StKillReal** [comment] 2024-06-07 13:30
@imDaniX Спасибо за 1.20.6, дружище
